# get all list
GET   {{url}}/api/v1/app-store
content-type: application/json
Authorization: Bearer {{token}}

### get id 

GET   {{url}}/api/v1/app-store/1
content-type: application/json
Authorization: Bearer {{token}}

### delete id 

DELETE    {{url}}/api/v1/app-store/1
content-type: application/json
Authorization: Bearer {{token}}

### create success

POST    {{url}}/api/v1/app-store
content-type: application/json
Authorization: Bearer {{token}}

< json/create.json

### create error

POST    {{url}}/api/v1/app-store
content-type: application/json
Authorization: Bearer {{token}}

< json/create-err.json

###

POST    {{url}}/api/v1/app-store/1
content-type: application/json
Authorization: Bearer {{token}}

< json/update.json
