GET   {{url}}/api/v1/application
content-type: application/json
Authorization: Bearer {{token}}

###

GET   {{url}}/api/v1/application/1
content-type: application/json
Authorization: Bearer {{token}}

###

DELETE    {{url}}/api/v1/application/1
content-type: application/json
Authorization: Bearer {{token}}

###

POST    {{url}}/api/v1/application
content-type: application/json
Authorization: Bearer {{token}}

< json/create.json

###

POST    {{url}}/api/v1/application/1
content-type: application/json
Authorization: Bearer {{token}}

< json/update.json
