GET   {{url}}/api/v1/config
content-type: application/json

### 

GET   {{url}}/api/v1/config/1
content-type: application/json

### 

DELETE    {{url}}/api/v1/config/1
content-type: application/json

### 

POST    {{url}}/api/v1/config
content-type: application/json

< json/create.json

### 

POST    {{url}}/api/v1/config/2
content-type: application/json

< json/update.json
