# get all scripts
GET   {{url}}/api/v1/scripts
content-type: application/json
Authorization: Bearer {{token}}

### get script by id

GET   {{url}}/api/v1/scripts/1
content-type: application/json
Authorization: Bearer {{token}}

### delete script

DELETE    {{url}}/api/v1/scripts/1
content-type: application/json
Authorization: Bearer {{token}}

### create script - success

POST    {{url}}/api/v1/scripts
content-type: application/json
Authorization: Bearer {{token}}

< json/create.json

### create script - error (no shebang)

POST    {{url}}/api/v1/scripts
content-type: application/json
Authorization: Bearer {{token}}

< json/create-err-no-shebang.json

### create script - error (empty content)

POST    {{url}}/api/v1/scripts
content-type: application/json
Authorization: Bearer {{token}}

< json/create-err-empty.json

### update script

POST    {{url}}/api/v1/scripts/1
content-type: application/json
Authorization: Bearer {{token}}

< json/update.json

### execute script on server

POST    {{url}}/api/v1/scripts/execute
content-type: application/json
Authorization: Bearer {{token}}

< json/execute.json

### get script execution results

GET   {{url}}/api/v1/scripts/1/results
content-type: application/json
Authorization: Bearer {{token}}

